name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Grant execute permission for gradlew
      run: chmod +x ./leistungsnachweis/gradlew 

    - name: Build with Gradle
      working-directory: ./leistungsnachweis
      run: |
        ./gradlew build

    - name: Pull Assessment Image
      run: docker pull mrksdh/assessment

      
    - name: Install curl
      run: |
        sudo apt-get update && sudo apt-get install -y curl

      
    - name: Create Docker Network
      run: |
        docker network create my_network

      
    - name: Start Assessment Container
      run: |
        docker run -d --name assessment --network my_network -p 8080:8080 mrksdh/assessment

    - name: Wait for Assessment Service to be healthy
      run: |
        timeout 120 sh -c 'until curl -sf http://localhost:8080/v1/dataset; do sleep 5; done'

    - name: Stop and remove Docker containers
      run: docker-compose down
