name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Schritt zum Feststellen des aktuellen Arbeitsverzeichnisses
    - name: Debug Working Directory
      run: pwd

    # Schritt zum Auflisten der Dateien im aktuellen Verzeichnis
    - name: List Files in Directory
      run: ls -al

    # Schritt, um sicherzustellen, dass gradlew ausführbar ist
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Schritt, um Gradle Wrapper Validation auszuführen
    - name: Run wrapperValidation
      run: ./gradlew wrapperValidation

    # Der restliche Build-Prozess
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Build Docker Image
      run: docker build -t leistungsnachweis .

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for Assessment Service to be healthy
      run: |
        timeout 60 sh -c 'until curl -s http://localhost:8080/v1/dataset; do sleep 5; done'

    - name: Run Leistungsnachweis Service
      run: |
        docker-compose up leistungsnachweis
